[package]
name = "continuate"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_op_in_unsafe_fn = "forbid"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
multiple_unsafe_ops_per_block = "deny"
option_if_let_else = "allow"
redundant_pub_crate = "allow"
undocumented_unsafe_blocks = "deny"
use_self = "allow"
