[package]
name = "continuate"
version.workspace = true
edition = "2021"

[dependencies]
continuate-arena = { version = "0.1.0", path = "./continuate-arena" }
continuate-backend = { version = "0.1.0", path = "./continuate-backend" }
continuate-frontend = { version = "0.1.0", path = "./continuate-frontend" }
continuate-ir = { version = "0.1.0", path = "./continuate-ir" }
log = { workspace = true }
simple_logger = { workspace = true }

[lints]
workspace = true

[workspace]
members = [
    "continuate-arena",
    "continuate-arena-macros",
    "continuate-backend",
    "continuate-error",
    "continuate-frontend",
    "continuate-ir",
    "continuate-rt",
    "continuate-rt-common",
]
resolver = "2"
package.version = "0.1.0"

[workspace.dependencies]
chumsky = { version = "1.0.0-alpha.7", features = ["nightly"] }
itertools = "0.13.0"
log = "0.4.21"
simple_logger = { version = "5.0.0", features = ["colors", "stderr"] }

[profile.dev.package."*"]
opt-level = 3

[profile.ci]
inherits = "dev"

[profile.ci.package."*"]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = "debuginfo"
codegen-units = 1

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "forbid"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
dbg_macro = "warn"
inline_always = "allow"
multiple_unsafe_ops_per_block = "deny"
must_use_candidate = "allow"
option_if_let_else = "allow"
redundant_pub_crate = "allow"
todo = "warn"
undocumented_unsafe_blocks = "deny"
use_self = "allow"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
