[package]
name = "continuate"
version.workspace = true
edition = "2021"

[dependencies]
continuate-arena = { version = "0.1.0", path = "./continuate-arena" }
continuate-backend = { version = "0.1.0", path = "./continuate-backend" }
continuate-ir = { version = "0.1.0", path = "./continuate-ir" }
log = "0.4.21"
simple_logger = { version = "4.3.3", features = ["colored"] }

[lints]
workspace = true

[workspace]
members = ["continuate-arena", "continuate-arena-macros", "continuate-ir", "continuate-error", "continuate-backend", "continuate-rt-common", "continuate-rt"]
resolver = "2"
package.version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "forbid"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
dbg_macro = "warn"
inline_always = "allow"
multiple_unsafe_ops_per_block = "deny"
must_use_candidate = "allow"
option_if_let_else = "allow"
redundant_pub_crate = "allow"
todo = "warn"
undocumented_unsafe_blocks = "deny"
use_self = "allow"
