[package]
name = "continuate-rt-common"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
bytemuck = "1.15.0"
continuate-arena = { workspace = true }

[lints]
workspace = true
