[package]
name = "continuate-rt-common"
edition = "2021"
version.workspace = true

[dependencies]
bytemuck = "1.15.0"
continuate-arena = { version = "0.1.0", path = "../continuate-arena" }

[lints]
workspace = true
