[package]
name = "continuate-arena"
version.workspace = true
edition = "2021"

[dependencies]
continuate-arena-macros = { version = "0.1.0", path = "../continuate-arena-macros" }

[lints]
workspace = true
