[package]
name = "continuate-arena-macros"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.35"
syn = { version = "2.0.58", features = ["extra-traits", "visit-mut"] }

[lints]
workspace = true
