[package]
name = "continuate-frontend"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
chumsky = { workspace = true }
continuate-error = { workspace = true }
logos = "0.14.0"

[lints]
workspace = true
