[package]
name = "continuate-frontend"
version.workspace = true
edition = "2021"
license.workspace = true
rust-version.workspace = true

[dependencies]
chumsky.workspace = true
continuate-error.workspace = true
logos = "0.14.1"

[lints]
workspace = true
