[package]
name = "continuate-common"
version.workspace = true
edition = "2021"
license.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = "1.17.0"
tracing-subscriber = { workspace = true }

[lints]
workspace = true
