[package]
name = "continuate-backend"
edition = "2021"
version.workspace = true

[dependencies]
continuate-arena = { workspace = true }
continuate-ir = { workspace = true }
continuate-rt-common = { workspace = true }
cranelift = "0.107.0"
cranelift-module = "0.107.0"
cranelift-object = "0.107.0"
itertools = { workspace = true }
log = { workspace = true }
target-lexicon = "0.12.14"

[lints]
workspace = true
