[package]
name = "continuate-backend"
edition = "2021"
version.workspace = true

[dependencies]
continuate-arena = { version = "0.1.0", path = "../continuate-arena" }
continuate-ir = { version = "0.1.0", path = "../continuate-ir" }
continuate-rt-common = { version = "0.1.0", path = "../continuate-rt-common" }
cranelift = "0.107.0"
cranelift-module = "0.107.0"
cranelift-object = "0.107.0"
itertools = { workspace = true }
log = { workspace = true }
target-lexicon = "0.12.14"

[lints]
workspace = true
