[package]
name = "continuate-backend"
version.workspace = true
edition = "2021"
license.workspace = true
rust-version.workspace = true

[dependencies]
bumpalo.workspace = true
continuate-common.workspace = true
continuate-ir.workspace = true
cranelift = "0.107.0"
cranelift-module = "0.107.0"
cranelift-object = "0.107.0"
itertools.workspace = true
tracing.workspace = true
target-lexicon = "0.12.14"

[lints]
workspace = true
