[package]
name = "continuate-backend"
version.workspace = true
edition = "2021"
license.workspace = true
rust-version.workspace = true

[dependencies]
bumpalo = "3.17.0"
continuate-ir.workspace = true
continuate-rt.workspace = true
cranelift = "0.118.0"
cranelift-module = "0.118.0"
cranelift-object = "0.118.0"
itertools.workspace = true
tracing.workspace = true
target-lexicon = "0.13.1" # Must be matched to cranelift-codegen/dep:target-lexicon

[lints]
workspace = true
