[package]
name = "continuate-ir"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
bimap = "0.6.3"
continuate-arena = { workspace = true }
continuate-error = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
