[package]
name = "continuate-ir"
version.workspace = true
edition = "2021"
license.workspace = true
rust-version.workspace = true

[dependencies]
continuate-error.workspace = true
continuate-frontend.workspace = true
itertools.workspace = true

[lints]
workspace = true
