[package]
name = "continuate-utils"
edition = "2024"
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bumpalo.workspace = true
hashbrown.workspace = true

[lints]
workspace = true
