name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        rustup toolchain add stable --component clippy
        rustup override set stable
    - name: Build runtime
      run: cargo build --verbose -p continuate-rt
    - name: Build
      run: cargo build --verbose --profile ci
    - name: Run tests
      run: cargo test --verbose --workspace --profile ci
    - name: Run Clippy
      run: cargo clippy --verbose --workspace --profile ci

  miri:
    name: Test with Miri
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          rustup toolchain add nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run Miri
        run: cargo miri test --verbose --workspace --profile ci
