[package]
name = "continuate-rt"
version.workspace = true
edition = "2021"
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
continuate-rt-common = { workspace = true }
log = { workspace = true }
simple_logger = { workspace = true }

[lints]
workspace = true
