[package]
name = "continuate-rt"
version.workspace = true
edition = "2021"
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
continuate-common = { workspace = true }
mimalloc = "0.1.42"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
